import type { Department } from './data'

export type ExpertIntent='greeting'|'explain'|'strategy'|'plan'|'teach'|'diagnose'|'create'|'consult'
type GlossaryEntry={term:string;aliases:string[];definition:string;example?:string}
type ExpertProfile={mission:string;scope:string[];methods:string[];handoffs:string[];glossary:GlossaryEntry[]}

const profiles:Record<string,ExpertProfile>={
  ceo:{mission:'dirigir la empresa, convertir señales en decisiones y coordinar a los directores especializados',scope:['estrategia empresarial','prioridades ejecutivas','KPIs y objetivos','gobernanza','delegación y seguimiento'],methods:['diagnóstico 360°','priorización impacto-esfuerzo-riesgo','OKR/KPI','escenarios ejecutivos'],handoffs:['STERLING','TALENT','JUSTITIA','ORBIT','NEXUS'],glossary:[{term:'KPI',aliases:['indicador','indicador clave'],definition:'métrica clave que permite evaluar si un objetivo empresarial avanza en la dirección esperada.'},{term:'gobernanza',aliases:['governance'],definition:'conjunto de reglas, responsabilidades y controles que determina cómo se toman, aprueban y auditan las decisiones.'}]},
  finanzas:{mission:'proteger liquidez, rentabilidad y capacidad financiera de la empresa',scope:['flujo de caja','liquidez','tesorería','capital de trabajo','presupuesto','rentabilidad','forecast financiero'],methods:['cash-flow forecast','análisis de escenarios','working capital','variance analysis','unit economics'],handoffs:['LEDGER','INVOICER','CLOSER','AURORA'],glossary:[{term:'flujo de caja',aliases:['cash flow'],definition:'movimiento real de entradas y salidas de efectivo durante un periodo; muestra si la empresa puede cumplir sus obligaciones.'},{term:'capital de trabajo',aliases:['working capital'],definition:'recursos de corto plazo disponibles para operar; normalmente se analiza como activos circulantes menos pasivos circulantes.'},{term:'EBITDA',aliases:['ebitda'],definition:'aproximación al desempeño operativo antes de intereses, impuestos, depreciación y amortización.'},{term:'runway',aliases:['pista financiera'],definition:'tiempo estimado que una empresa puede seguir operando con la caja disponible al ritmo actual de consumo.'}]},
  rrhh:{mission:'desarrollar talento, estructura organizacional y capacidad humana sostenible',scope:['competencias','desempeño','rotación','organigrama','compensación','clima laboral','planes de carrera'],methods:['matriz 9-box','competency mapping','people analytics','succession planning','employee journey'],handoffs:['ACADEMY','PAYROLL','JUSTITIA','AURORA'],glossary:[{term:'competencia',aliases:['skill','habilidad'],definition:'combinación demostrable de conocimiento, habilidad y conducta necesaria para desempeñar una función.'},{term:'rotación',aliases:['turnover'],definition:'salida y reemplazo de personas en una organización durante un periodo determinado.'},{term:'plan de carrera',aliases:['career path'],definition:'ruta estructurada de crecimiento profesional con competencias, experiencias y criterios de avance.'}]},
  legal:{mission:'reducir riesgo jurídico y convertir obligaciones legales y contractuales en acciones controlables',scope:['contratos','cláusulas','obligaciones','riesgo jurídico','evidencia','cumplimiento corporativo'],methods:['issue spotting','contract review','matriz de obligaciones','legal risk assessment','evidence-first analysis'],handoffs:['NORM','ARCHIVE','SOURCE','AURORA'],glossary:[{term:'cláusula',aliases:['clausula'],definition:'disposición específica de un contrato que establece derechos, obligaciones, condiciones o consecuencias para las partes.'},{term:'cláusula de renovación',aliases:['renovacion automatica','renovación automática'],definition:'disposición que define si, cuándo y bajo qué condiciones un contrato se prorroga o renueva.'},{term:'obligación',aliases:['obligacion'],definition:'deber exigible que una parte debe cumplir conforme a una norma, contrato o acto jurídico.'}]},
  contabilidad:{mission:'mantener integridad contable, cierres confiables y trazabilidad financiera',scope:['libro mayor','pólizas','conciliaciones','devengo','estados financieros','cierre contable'],methods:['double-entry review','account reconciliation','continuous close','variance review'],handoffs:['STERLING','INVOICER','PAYROLL','NORM'],glossary:[{term:'devengo',aliases:['accrual'],definition:'principio por el que ingresos y gastos se reconocen cuando se generan, no únicamente cuando se cobran o pagan.'},{term:'conciliación',aliases:['conciliacion'],definition:'comparación de dos fuentes de información para identificar y resolver diferencias.'},{term:'póliza',aliases:['poliza contable','asiento'],definition:'registro estructurado de cargos y abonos que documenta una operación contable.'}]},
  facturacion:{mission:'convertir ventas en facturación correcta y cobranza oportuna',scope:['CFDI','cuentas por cobrar','cartera vencida','pagos','complementos','notas de crédito'],methods:['aging de cartera','collection prioritization','invoice validation','dunning strategy'],handoffs:['CLOSER','STERLING','LEDGER','JUSTITIA'],glossary:[{term:'CFDI',aliases:['factura fiscal'],definition:'Comprobante Fiscal Digital por Internet utilizado en México para documentar fiscalmente operaciones.'},{term:'cartera vencida',aliases:['overdue receivables'],definition:'cuentas por cobrar cuya fecha pactada de pago ya pasó sin liquidación completa.'},{term:'complemento de pago',aliases:['complemento'],definition:'CFDI que documenta la recepción de pagos relacionados con comprobantes emitidos bajo los supuestos aplicables.'}]},
  nominas:{mission:'procesar compensación laboral con consistencia, evidencia y coordinación con Recursos Humanos',scope:['pre-nómina','incidencias','percepciones','deducciones','finiquitos','periodos de nómina'],methods:['pre-payroll validation','incident reconciliation','variance checks','period close'],handoffs:['TALENT','LEDGER','STERLING','JUSTITIA'],glossary:[{term:'pre-nómina',aliases:['prenomina'],definition:'cálculo preliminar que integra incidencias, percepciones y deducciones antes de cerrar la nómina.'},{term:'incidencia',aliases:['incidencia de nómina'],definition:'evento que modifica el cálculo normal de pago, como ausencia, bono, incapacidad, horas extra o descuento.'},{term:'finiquito',aliases:['settlement'],definition:'liquidación de conceptos pendientes al terminar una relación laboral, según la causa y normativa aplicable.'}]},
  inventarios:{mission:'mantener disponibilidad de producto con el menor capital inmovilizado y riesgo de ruptura posible',scope:['stock','almacenes','movimientos','reposición','rotación','merma'],methods:['ABC/XYZ','reorder point','safety stock','inventory turnover','cycle counting'],handoffs:['PROCURE','SOURCE','ORBIT','STERLING'],glossary:[{term:'stock de seguridad',aliases:['safety stock'],definition:'inventario adicional mantenido para absorber variabilidad de demanda o suministro.'},{term:'punto de reorden',aliases:['reorder point'],definition:'nivel de inventario que dispara una reposición considerando demanda durante el lead time y stock de seguridad.'},{term:'rotación de inventario',aliases:['inventory turnover'],definition:'frecuencia con la que el inventario se vende o consume y se repone durante un periodo.'}]},
  proveedores:{mission:'construir una red de proveedores confiable, competitiva y controlada por riesgo',scope:['evaluación de proveedores','SLA','TCO','contratos','riesgo de suministro','sourcing'],methods:['supplier scorecard','TCO analysis','concentration risk','SLA review'],handoffs:['PROCURE','JUSTITIA','NORM','STERLING'],glossary:[{term:'SLA',aliases:['acuerdo de nivel de servicio'],definition:'compromiso medible de nivel de servicio, por ejemplo disponibilidad, tiempo de respuesta o resolución.'},{term:'TCO',aliases:['costo total de propiedad'],definition:'costo total de adquirir, operar, mantener y retirar un producto o servicio, no solo su precio de compra.'},{term:'scorecard',aliases:['evaluación de proveedor'],definition:'matriz de indicadores para evaluar desempeño, calidad, entrega, riesgo y cumplimiento de un proveedor.'}]},
  compras:{mission:'convertir necesidades internas en compras controladas, competitivas y trazables',scope:['requisiciones','RFQ','órdenes de compra','aprobaciones','recepción','three-way match'],methods:['competitive sourcing','approval matrix','PO governance','three-way match'],handoffs:['SOURCE','MERIDIAN','LEDGER','STERLING'],glossary:[{term:'RFQ',aliases:['request for quotation','solicitud de cotización'],definition:'proceso formal para solicitar y comparar cotizaciones de proveedores.'},{term:'orden de compra',aliases:['oc','purchase order'],definition:'documento autorizado que formaliza qué se compra, a quién, en qué cantidad, precio y condiciones.'},{term:'three-way match',aliases:['3-way match'],definition:'comparación entre orden de compra, recepción e invoice/factura del proveedor antes de aprobar el pago.'}]},
  activos:{mission:'maximizar valor, control y trazabilidad del ciclo de vida de los activos empresariales',scope:['activos fijos','custodia','mantenimiento','depreciación','vida útil','TCO'],methods:['asset lifecycle','criticality assessment','TCO analysis','maintenance planning'],handoffs:['PROCURE','LEDGER','NEXUS','SENTINEL'],glossary:[{term:'vida útil',aliases:['useful life'],definition:'periodo durante el cual se espera que un activo aporte utilidad económica u operativa.'},{term:'depreciación',aliases:['depreciacion'],definition:'distribución sistemática del importe depreciable de un activo durante su vida útil bajo la política aplicable.'},{term:'custodia',aliases:['asset custody'],definition:'responsabilidad formal sobre el uso, resguardo y trazabilidad de un activo asignado.'}]},
  atencion:{mission:'resolver necesidades del cliente con velocidad, contexto y enfoque en retención',scope:['tickets','SLA','Customer 360','sentimiento','CSAT','NPS','churn','escalamientos'],methods:['case prioritization','service recovery','root cause','customer health'],handoffs:['CLOSER','NEXUS','INVOICER','AURORA'],glossary:[{term:'CSAT',aliases:['satisfacción'],definition:'indicador de satisfacción del cliente normalmente capturado después de una interacción o servicio.'},{term:'NPS',aliases:['net promoter score'],definition:'métrica de disposición a recomendar una marca o servicio basada en promotores, pasivos y detractores.'},{term:'churn',aliases:['abandono','cancelación'],definition:'pérdida de clientes o ingresos recurrentes por cancelación o no renovación.'},{term:'customer health',aliases:['salud del cliente'],definition:'señal compuesta sobre adopción, satisfacción, soporte, riesgo y valor de una cuenta.'}]},
  marketing:{mission:'convertir mercado y atención en demanda rentable y aprendizaje de crecimiento',scope:['campañas','CAC','ROAS','funnel','atribución','contenido','audiencias','experimentos'],methods:['full-funnel analysis','experimentation','attribution review','creative testing'],handoffs:['CLOSER','CARE','STERLING','INSIGHT'],glossary:[{term:'CAC',aliases:['costo de adquisición'],definition:'costo promedio de adquirir un cliente, considerando el gasto atribuible al proceso de captación.'},{term:'ROAS',aliases:['return on ad spend'],definition:'ingresos atribuidos a publicidad divididos entre el gasto publicitario; no prueba causalidad por sí solo.'},{term:'MQL',aliases:['marketing qualified lead'],definition:'lead que cumple criterios de marketing para considerarse con mayor probabilidad de avanzar comercialmente.'},{term:'atribución',aliases:['attribution'],definition:'método para asignar crédito de una conversión a uno o varios puntos de contacto.'}]},
  ventas:{mission:'convertir oportunidades calificadas en ingresos predecibles y relaciones de largo plazo',scope:['CRM','pipeline','forecast','oportunidades','cuentas','deal health','win/loss'],methods:['qualification','pipeline inspection','forecast discipline','account planning'],handoffs:['PULSE','CARE','JUSTITIA','INVOICER','STERLING'],glossary:[{term:'pipeline',aliases:['embudo comercial'],definition:'conjunto de oportunidades comerciales abiertas organizadas por etapa y probabilidad de avance.'},{term:'forecast',aliases:['pronóstico de ventas'],definition:'estimación de ingresos futuros basada en oportunidades, probabilidad, evidencia y fecha esperada de cierre.'},{term:'champion',aliases:['patrocinador interno'],definition:'persona dentro de la cuenta que impulsa activamente la solución y ayuda a navegar el proceso de compra.'},{term:'deal health',aliases:['salud de oportunidad'],definition:'evaluación compuesta de calidad y riesgo de una oportunidad usando etapa, actividad, sponsor, competencia y siguientes pasos.'}]},
  proyectos:{mission:'entregar portafolios y proyectos con valor, control de dependencias y uso responsable de recursos',scope:['portafolio','roadmap','milestones','critical path','RAID','capacidad','presupuesto'],methods:['critical path method','RAID','portfolio prioritization','capacity planning'],handoffs:['STERLING','TALENT','ORBIT','AURORA'],glossary:[{term:'ruta crítica',aliases:['critical path'],definition:'secuencia de actividades que determina la duración mínima de un proyecto; un retraso en ella puede mover la fecha final.'},{term:'milestone',aliases:['hito'],definition:'punto de control significativo que marca un resultado, decisión o etapa importante del proyecto.'},{term:'RAID',aliases:['raid log'],definition:'registro estructurado de riesgos, supuestos, issues/incidencias y dependencias.'}]},
  analitica:{mission:'convertir datos en decisiones explicables sin confundir correlación con causalidad',scope:['KPIs','anomalías','drivers','forecast','escenarios','calidad del dato'],methods:['descriptive analytics','driver analysis','forecast intervals','scenario analysis'],handoffs:['AURORA','STERLING','PULSE','ORBIT'],glossary:[{term:'anomalía',aliases:['anomalia','outlier'],definition:'observación o patrón que se desvía de manera relevante del comportamiento esperado y merece investigación.'},{term:'correlación',aliases:['correlacion'],definition:'relación estadística entre variables; por sí sola no demuestra que una cause a la otra.'},{term:'intervalo de confianza',aliases:['confidence interval'],definition:'rango que expresa incertidumbre alrededor de una estimación bajo supuestos estadísticos determinados.'}]},
  documentos:{mission:'convertir documentos en conocimiento trazable, versionado y citable',scope:['ingesta','OCR','RAG','extracción','versionado','redline','obligaciones','evidence graph'],methods:['document passport','structured extraction','version comparison','evidence mapping'],handoffs:['JUSTITIA','NORM','AURORA','NEXUS'],glossary:[{term:'OCR',aliases:['reconocimiento óptico'],definition:'tecnología que convierte texto contenido en imágenes o documentos escaneados en texto procesable.'},{term:'RAG',aliases:['retrieval augmented generation'],definition:'arquitectura que recupera evidencia relevante antes de generar una respuesta para mejorar grounding y trazabilidad.'},{term:'redline',aliases:['comparación de versiones'],definition:'comparación que resalta cambios entre dos versiones de un documento.'},{term:'evidence graph',aliases:['grafo de evidencia'],definition:'mapa de relaciones entre documentos, hechos, obligaciones, entidades y fuentes con trazabilidad.'}]},
  capacitacion:{mission:'cerrar brechas de competencias y convertir aprendizaje en capacidad demostrable',scope:['skills','skill gaps','rutas de aprendizaje','cursos','evaluaciones','certificaciones','simulaciones'],methods:['competency mapping','adaptive learning path','assessment design','transfer of learning'],handoffs:['TALENT','NORM','SENTINEL','PMO','NEXUS'],glossary:[{term:'skill gap',aliases:['brecha de competencia','brecha de habilidad'],definition:'diferencia entre el nivel de competencia que una persona o rol necesita y el nivel que actualmente demuestra.',example:'Si un rol requiere nivel 4 en seguridad y la evaluación demuestra nivel 2, existe una brecha de 2 niveles.'},{term:'ruta de aprendizaje',aliases:['learning path'],definition:'secuencia estructurada de contenidos, práctica, evaluación y evidencia diseñada para alcanzar competencias concretas.'},{term:'assessment',aliases:['evaluación'],definition:'mecanismo para medir conocimiento, habilidad o desempeño respecto a criterios definidos.'},{term:'upskilling',aliases:['mejora de habilidades'],definition:'desarrollo de competencias para desempeñar mejor o ampliar el alcance del rol actual.'},{term:'reskilling',aliases:['reconversión'],definition:'aprendizaje de competencias para desempeñar un rol distinto o una función significativamente diferente.'}]},
  seguridad:{mission:'reducir exposición cibernética priorizando activos, identidades, vulnerabilidades y controles',scope:['IAM','vulnerabilidades','incidentes','attack paths','Zero Trust','controles','activos críticos'],methods:['risk-based vulnerability management','incident response','attack path analysis','least privilege'],handoffs:['NEXUS','NORM','APEX','AURORA'],glossary:[{term:'attack path',aliases:['ruta de ataque'],definition:'secuencia plausible de condiciones y accesos que podría permitir a un atacante avanzar desde un punto de entrada hacia un activo objetivo; no demuestra que el ataque haya ocurrido.'},{term:'IAM',aliases:['identity and access management'],definition:'disciplina y tecnología para gestionar identidades, autenticación, autorización y privilegios.'},{term:'Zero Trust',aliases:['confianza cero'],definition:'modelo que evita confiar implícitamente por ubicación de red y exige verificación continua de identidad, contexto y acceso.'}]},
  compliance:{mission:'demostrar cumplimiento mediante obligaciones, controles, pruebas y evidencia verificable',scope:['frameworks','controles','obligaciones','evidencia','auditorías','excepciones','riesgo residual'],methods:['control mapping','evidence readiness','control testing','risk acceptance'],handoffs:['SENTINEL','JUSTITIA','ARCHIVE','AURORA'],glossary:[{term:'control',aliases:['control interno'],definition:'medida diseñada para prevenir, detectar o responder a un riesgo u obligación.'},{term:'riesgo residual',aliases:['residual risk'],definition:'riesgo que permanece después de aplicar los controles existentes.'},{term:'excepción',aliases:['exception'],definition:'desviación temporal y autorizada de una política o control, que debe documentar riesgo, compensaciones, responsable y vencimiento.'}]},
  operaciones:{mission:'mejorar flujo operativo, capacidad y cumplimiento de servicio de punta a punta',scope:['procesos','throughput','cycle time','WIP','bottlenecks','capacidad','SLA','colas'],methods:['process flow analysis','queue aging','capacity planning','digital twin what-if'],handoffs:['PMO','TALENT','CARE','MERIDIAN','NEXUS'],glossary:[{term:'throughput',aliases:['tasa de salida'],definition:'cantidad de unidades o casos que un proceso completa por unidad de tiempo.'},{term:'cycle time',aliases:['tiempo de ciclo'],definition:'tiempo transcurrido desde que una unidad entra a una etapa o proceso hasta que sale completada.'},{term:'WIP',aliases:['work in progress','trabajo en proceso'],definition:'cantidad de trabajo iniciado que todavía no ha terminado.'},{term:'cuello de botella',aliases:['bottleneck'],definition:'restricción que limita el throughput global de un proceso.'}]},
  tecnologia:{mission:'mantener una plataforma tecnológica confiable, observable, segura y evolutiva',scope:['arquitectura','APIs','SLOs','observabilidad','releases','dependencias','deuda técnica','resiliencia AI'],methods:['SLO/error budget','dependency mapping','release governance','technical debt prioritization'],handoffs:['SENTINEL','ORBIT','PMO','AURORA'],glossary:[{term:'SLO',aliases:['service level objective'],definition:'objetivo medible de confiabilidad o desempeño de un servicio durante una ventana definida.'},{term:'observabilidad',aliases:['observability'],definition:'capacidad de entender el estado interno de un sistema a partir de métricas, logs, traces y señales correlacionadas.'},{term:'deuda técnica',aliases:['technical debt'],definition:'costo futuro creado por decisiones técnicas que aceleran el presente pero requieren corrección o inversión posterior.'},{term:'circuit breaker',aliases:['cortacircuito'],definition:'patrón de resiliencia que detiene temporalmente llamadas a una dependencia degradada para evitar fallos en cascada.'}]},
}

function norm(value:string){return value.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[¿?¡!.,;:()]/g,' ').replace(/\s+/g,' ').trim()}

export function detectExpertIntent(text:string):ExpertIntent{
  const t=norm(text)
  if(/^(hola|buenas|buenos dias|buen dia|hey|que tal|saludos)(\s|$)/.test(t))return'greeting'
  if(/\b(ensename|capacita|capacitar|curso|tutorial|aprender|como trabajar|entrename|formacion)\b/.test(t))return'teach'
  if(/\b(estrategia|estrategico|optimizar|mejorar|crecer|reducir|aumentar|potenciar)\b/.test(t))return'strategy'
  if(/\b(plan|pasos|roadmap|implementar|programa|cronograma|hoja de ruta)\b/.test(t))return'plan'
  if(/\b(que es|explica|explicame|concepto|como funciona|diferencia|significa)\b/.test(t))return'explain'
  if(/\b(analiza|diagnostica|diagnostico|problema|riesgo|por que|causa|detecta|evalua)\b/.test(t))return'diagnose'
  if(/\b(crea|disena|haz|prepara|redacta|construye|genera)\b/.test(t))return'create'
  return'consult'
}

function profileFor(department:Department){return profiles[department.id]??{mission:department.description,scope:department.capabilities,methods:department.automations,handoffs:['AURORA'],glossary:[]}}
function matchedTerm(profile:ExpertProfile,text:string){const t=norm(text);return profile.glossary.find(g=>[g.term,...g.aliases].some(a=>t.includes(norm(a))))}
function numbered(items:string[]){return items.map((x,i)=>`${i+1}. ${x}`).join('\n')}
function capabilities(department:Department){return department.capabilities.slice(0,5).join(', ')}

export function buildDepartmentExpertResponse(department:Department,text:string):string{
  const profile=profileFor(department)
  const intent=detectExpertIntent(text)
  const term=matchedTerm(profile,text)
  const agent=department.agent

  if(intent==='greeting')return `Hola. Soy ${agent}, ${department.role}. Mi especialidad es ${department.name}.\n\nPuedo explicarte conceptos, diagnosticar problemas, diseñar estrategias, convertirlas en planes paso a paso y enseñarte a trabajar con métodos de ${department.name}. Mis áreas principales son: ${profile.scope.slice(0,5).join(', ')}.\n\nDime qué quieres entender, mejorar, crear o aprender y trabajamos directamente sobre ello.`

  if(intent==='explain'){
    if(term)return `${term.term}\n${term.definition}${term.example?`\n\nEjemplo práctico: ${term.example}`:''}\n\nEn ${department.name}, normalmente lo conectaría con ${profile.scope.slice(0,3).join(', ')}. Si quieres, puedo explicártelo desde cero, compararlo con otro concepto o llevarlo a un caso práctico.`
    return `Te lo explico desde la perspectiva de ${department.name}.\n\n${department.description}\n\nPara entender bien el tema conviene separar cuatro piezas:\n${numbered(profile.scope.slice(0,4).map(x=>`${x}: qué es, cómo se mide y qué decisión permite tomar.`))}\n\nSi me indicas el concepto exacto, te doy definición, ejemplo práctico, errores comunes y cómo aplicarlo.`
  }

  if(intent==='teach')return `Modo capacitación · ${agent}\nObjetivo: que puedas aplicar el tema, no solo memorizarlo.\n\nRuta sugerida:\n${numbered([
    `Fundamento: entender ${profile.scope[0]??department.name} y su relación con el resultado del área.`,
    `Método: practicar ${profile.methods[0]??department.capabilities[0]??'el proceso principal'} con un caso guiado.`,
    `Aplicación: resolver un escenario real de ${department.name} con criterios y evidencia.`,
    `Evaluación: comprobar que puedes explicar la decisión y ejecutar el procedimiento sin depender de una plantilla.`,
    `Transferencia al puesto: convertir lo aprendido en checklist, KPI o rutina operativa.`
  ])}\n\nPuedo darte la clase paso a paso. Dime el nivel que quieres: inicial, operativo, avanzado o experto.`

  if(intent==='strategy')return `Estrategia propuesta · ${department.name}\n\nObjetivo: mejorar el resultado del área sin perder control ni trazabilidad.\n\n${numbered([
    `Diagnóstico base: medir ${profile.scope.slice(0,3).join(', ')} y definir una línea de referencia.`,
    `Prioridad: identificar el cuello de botella o riesgo con mayor impacto económico u operativo.`,
    `Diseño: aplicar ${profile.methods.slice(0,2).join(' + ')} con responsables y criterios de decisión.`,
    `Ejecución: convertir la estrategia en iniciativas de 30, 60 y 90 días con owner y evidencia.`,
    `Control: revisar KPIs, desviaciones, riesgos y aprendizaje antes de escalar la siguiente inversión.`
  ])}\n\nIndicadores sugeridos: ${department.capabilities.slice(0,3).join(' · ')}. Si me das tu objetivo concreto, la convierto en una estrategia específica con metas y escenarios.`

  if(intent==='plan')return `Plan de acción · ${department.name}\n\n${numbered([
    `Definir resultado esperado, alcance y criterio de éxito.`,
    `Levantar datos y evidencia sobre ${profile.scope.slice(0,3).join(', ')}.`,
    `Priorizar acciones con ${profile.methods[0]??'un método de diagnóstico del área'}.`,
    `Asignar owner, fecha, KPI y dependencia a cada acción.`,
    `Ejecutar un primer ciclo corto y registrar bloqueos o desviaciones.`,
    `Revisar resultados, documentar aprendizaje y decidir si escalar, corregir o detener.`
  ])}\n\nEntregables recomendados: diagnóstico, plan 30-60-90, tablero de KPIs y registro de decisiones. Puedo construirlos contigo.`

  if(intent==='diagnose')return `Diagnóstico experto · ${department.name}\n\nAntes de concluir, revisaría estas señales:\n${numbered(profile.scope.slice(0,6).map(x=>`${x}: estado actual, tendencia, desviación y evidencia disponible.`))}\n\nDespués separaría hechos, hipótesis y decisiones. El resultado debe indicar: problema raíz probable, impacto, prioridad, owner, acción inmediata y métrica de recuperación.\n\nSi compartes el caso o los datos, hago el diagnóstico contigo sin inventar información.`

  if(intent==='create')return `Puedo construir ese entregable desde ${department.name}.\n\nEstructura profesional recomendada:\n${numbered([
    'Objetivo y resultado esperado.',
    `Contexto técnico de ${profile.scope.slice(0,3).join(', ')}.`,
    'Datos, supuestos y evidencia disponible.',
    `Método de trabajo: ${profile.methods.slice(0,2).join(' + ')}.`,
    'Plan de ejecución con responsables, fechas y KPIs.',
    'Riesgos, controles, dependencias y criterio de cierre.'
  ])}\n\nDime el resultado final que necesitas y lo desarrollo en formato listo para usar.`

  if(term)return `${term.term}: ${term.definition}\n\nDesde ${department.name}, puedo llevar este concepto a diagnóstico, estrategia, plan, capacitación o un entregable concreto.`

  return `Entiendo la consulta desde ${department.name}. Mi función como ${agent} es ${profile.mission}.\n\nPuedo ayudarte en ${capabilities(department)} y profundizar en ${profile.scope.slice(0,5).join(', ')}. Para una respuesta útil voy a trabajar con contexto, método y resultado esperado, no con una respuesta genérica.\n\nSobre tu mensaje: “${text}”. Dime si quieres que lo abordemos como explicación, diagnóstico, estrategia, plan o capacitación y continúo directamente.`
}

export function buildDepartmentSystemPrompt(department:Department):string{
  const profile=profileFor(department)
  return `Eres ${department.agent}, ${department.role} de WAE OS Enterprise. Tu dominio principal es ${department.name}. Tu misión es ${profile.mission}. Debes responder como especialista y profesor práctico: explicar conceptos con claridad, diagnosticar, diseñar estrategias, crear planes accionables, enseñar procedimientos y producir entregables propios del área. Dominios: ${profile.scope.join(', ')}. Métodos: ${profile.methods.join(', ')}. Capacidades declaradas: ${department.capabilities.join(', ')}. Mantente dentro de tu especialidad; si una decisión requiere otra disciplina, indica el handoff apropiado entre ${profile.handoffs.join(', ')}, pero primero resuelve la parte que sí corresponde a tu módulo. Distingue hechos de supuestos, no inventes datos, integraciones ni evidencia. Las acciones sensibles requieren autorización y trazabilidad.`
}

export function expertModePrompts(department:Department){
  return [
    `Explícame un concepto clave de ${department.name}`,
    `Diseña una estrategia de ${department.name}`,
    'Crea un plan paso a paso',
    `Enséñame a trabajar mejor en ${department.name}`,
  ]
}
